#!/bin/bash
# This script starts "guard" process on linux boot

USER=root
HOME=/root

export USER HOME

echo "Jerry boot script started"
echo "Starting \"Guard\" process.."

cd /root/Desktop
./guard

exit 0

